package main

import "time"

type JellySession struct {
	PlayState struct {
		PositionTicks       int64  `json:"PositionTicks"`
		CanSeek             bool   `json:"CanSeek"`
		IsPaused            bool   `json:"IsPaused"`
		IsMuted             bool   `json:"IsMuted"`
		VolumeLevel         int    `json:"VolumeLevel"`
		AudioStreamIndex    int    `json:"AudioStreamIndex"`
		SubtitleStreamIndex int    `json:"SubtitleStreamIndex"`
		MediaSourceID       string `json:"MediaSourceId"`
		PlayMethod          string `json:"PlayMethod"`
		RepeatMode          string `json:"RepeatMode"`
	} `json:"PlayState"`
	RemoteEndPoint      string    `json:"RemoteEndPoint"`
	UserName            string    `json:"UserName"`
	Client              string    `json:"Client"`
	LastActivityDate    time.Time `json:"LastActivityDate"`
	LastPlaybackCheckIn time.Time `json:"LastPlaybackCheckIn"`
	DeviceName          string    `json:"DeviceName"`
	NowPlayingItem      struct {
		Name          string    `json:"Name"`
		OriginalTitle string    `json:"OriginalTitle"`
		ServerID      string    `json:"ServerId"`
		ID            string    `json:"Id"`
		DateCreated   time.Time `json:"DateCreated"`
		HasSubtitles  bool      `json:"HasSubtitles"`
		Container     string    `json:"Container"`
		PremiereDate  time.Time `json:"PremiereDate"`
		ExternalUrls  []struct {
			Name string `json:"Name"`
			URL  string `json:"Url"`
		} `json:"ExternalUrls"`
		Path                     string   `json:"Path"`
		EnableMediaSourceDisplay bool     `json:"EnableMediaSourceDisplay"`
		ChannelID                any      `json:"ChannelId"`
		Overview                 string   `json:"Overview"`
		Taglines                 []string `json:"Taglines"`
		Genres                   []string `json:"Genres"`
		CommunityRating          float64  `json:"CommunityRating"`
		RunTimeTicks             int64    `json:"RunTimeTicks"`
		ProductionYear           int      `json:"ProductionYear"`
		ProviderIds              struct {
			Imdb string `json:"Imdb"`
			Tmdb string `json:"Tmdb"`
		} `json:"ProviderIds"`
		IsHD     bool   `json:"IsHD"`
		IsFolder bool   `json:"IsFolder"`
		ParentID string `json:"ParentId"`
		Type     string `json:"Type"`
		Studios  []struct {
			Name string `json:"Name"`
			ID   string `json:"Id"`
		} `json:"Studios"`
		GenreItems []struct {
			Name string `json:"Name"`
			ID   string `json:"Id"`
		} `json:"GenreItems"`
		LocalTrailerCount       int     `json:"LocalTrailerCount"`
		SpecialFeatureCount     int     `json:"SpecialFeatureCount"`
		PrimaryImageAspectRatio float64 `json:"PrimaryImageAspectRatio"`
		MediaStreams            []struct {
			Codec                  string  `json:"Codec"`
			Language               string  `json:"Language"`
			TimeBase               string  `json:"TimeBase"`
			LocalizedUndefined     string  `json:"LocalizedUndefined,omitempty"`
			LocalizedDefault       string  `json:"LocalizedDefault,omitempty"`
			LocalizedForced        string  `json:"LocalizedForced,omitempty"`
			LocalizedExternal      string  `json:"LocalizedExternal,omitempty"`
			DisplayTitle           string  `json:"DisplayTitle"`
			IsInterlaced           bool    `json:"IsInterlaced"`
			IsDefault              bool    `json:"IsDefault"`
			IsForced               bool    `json:"IsForced"`
			Type                   string  `json:"Type"`
			Index                  int     `json:"Index"`
			IsExternal             bool    `json:"IsExternal"`
			IsTextSubtitleStream   bool    `json:"IsTextSubtitleStream"`
			SupportsExternalStream bool    `json:"SupportsExternalStream"`
			Path                   string  `json:"Path,omitempty"`
			Level                  int     `json:"Level"`
			CodecTag               string  `json:"CodecTag,omitempty"`
			ColorSpace             string  `json:"ColorSpace,omitempty"`
			ColorTransfer          string  `json:"ColorTransfer,omitempty"`
			ColorPrimaries         string  `json:"ColorPrimaries,omitempty"`
			VideoRange             string  `json:"VideoRange,omitempty"`
			VideoRangeType         string  `json:"VideoRangeType,omitempty"`
			NalLengthSize          string  `json:"NalLengthSize,omitempty"`
			IsAVC                  bool    `json:"IsAVC,omitempty"`
			BitRate                int     `json:"BitRate,omitempty"`
			BitDepth               int     `json:"BitDepth,omitempty"`
			RefFrames              int     `json:"RefFrames,omitempty"`
			Height                 int     `json:"Height,omitempty"`
			Width                  int     `json:"Width,omitempty"`
			AverageFrameRate       float64 `json:"AverageFrameRate,omitempty"`
			RealFrameRate          float64 `json:"RealFrameRate,omitempty"`
			Profile                string  `json:"Profile,omitempty"`
			AspectRatio            string  `json:"AspectRatio,omitempty"`
			PixelFormat            string  `json:"PixelFormat,omitempty"`
			ChannelLayout          string  `json:"ChannelLayout,omitempty"`
			Channels               int     `json:"Channels,omitempty"`
			SampleRate             int     `json:"SampleRate,omitempty"`
		} `json:"MediaStreams"`
		VideoType    string `json:"VideoType"`
		LocationType string `json:"LocationType"`
		MediaType    string `json:"MediaType"`
		Width        int    `json:"Width"`
		Height       int    `json:"Height"`
	} `json:"NowPlayingItem"`
	FullNowPlayingItem struct {
		Size          int64     `json:"Size"`
		Container     string    `json:"Container"`
		IsHD          bool      `json:"IsHD"`
		IsShortcut    bool      `json:"IsShortcut"`
		Width         int       `json:"Width"`
		Height        int       `json:"Height"`
		ExtraIds      []any     `json:"ExtraIds"`
		DateLastSaved time.Time `json:"DateLastSaved"`
		Name          string    `json:"Name"`
	} `json:"FullNowPlayingItem"`
	DeviceID              string `json:"DeviceId"`
	ApplicationVersion    string `json:"ApplicationVersion"`
	IsActive              bool   `json:"IsActive"`
	SupportsMediaControl  bool   `json:"SupportsMediaControl"`
	SupportsRemoteControl bool   `json:"SupportsRemoteControl"`
	NowPlayingQueue       []struct {
		ID             string `json:"Id"`
		PlaylistItemID string `json:"PlaylistItemId"`
	} `json:"NowPlayingQueue"`
	NowPlayingQueueFullItems []struct {
		Name          string    `json:"Name"`
		OriginalTitle string    `json:"OriginalTitle"`
		ServerID      string    `json:"ServerId"`
		ID            string    `json:"Id"`
		Etag          string    `json:"Etag"`
		DateCreated   time.Time `json:"DateCreated"`
		CanDelete     bool      `json:"CanDelete"`
		CanDownload   bool      `json:"CanDownload"`
		HasSubtitles  bool      `json:"HasSubtitles"`
		Container     string    `json:"Container"`
		SortName      string    `json:"SortName"`
		PremiereDate  time.Time `json:"PremiereDate"`
		ExternalUrls  []struct {
			Name string `json:"Name"`
			URL  string `json:"Url"`
		} `json:"ExternalUrls"`
		MediaSources []struct {
			Protocol              string `json:"Protocol"`
			ID                    string `json:"Id"`
			Path                  string `json:"Path"`
			Type                  string `json:"Type"`
			Container             string `json:"Container"`
			Size                  int64  `json:"Size"`
			Name                  string `json:"Name"`
			IsRemote              bool   `json:"IsRemote"`
			ETag                  string `json:"ETag"`
			RunTimeTicks          int64  `json:"RunTimeTicks"`
			ReadAtNativeFramerate bool   `json:"ReadAtNativeFramerate"`
			IgnoreDts             bool   `json:"IgnoreDts"`
			IgnoreIndex           bool   `json:"IgnoreIndex"`
			GenPtsInput           bool   `json:"GenPtsInput"`
			SupportsTranscoding   bool   `json:"SupportsTranscoding"`
			SupportsDirectStream  bool   `json:"SupportsDirectStream"`
			SupportsDirectPlay    bool   `json:"SupportsDirectPlay"`
			IsInfiniteStream      bool   `json:"IsInfiniteStream"`
			RequiresOpening       bool   `json:"RequiresOpening"`
			RequiresClosing       bool   `json:"RequiresClosing"`
			RequiresLooping       bool   `json:"RequiresLooping"`
			SupportsProbing       bool   `json:"SupportsProbing"`
			VideoType             string `json:"VideoType"`
			MediaStreams          []struct {
				Codec                  string  `json:"Codec"`
				Language               string  `json:"Language,omitempty"`
				TimeBase               string  `json:"TimeBase"`
				LocalizedUndefined     string  `json:"LocalizedUndefined,omitempty"`
				LocalizedDefault       string  `json:"LocalizedDefault,omitempty"`
				LocalizedForced        string  `json:"LocalizedForced,omitempty"`
				LocalizedExternal      string  `json:"LocalizedExternal,omitempty"`
				DisplayTitle           string  `json:"DisplayTitle"`
				IsInterlaced           bool    `json:"IsInterlaced"`
				IsDefault              bool    `json:"IsDefault"`
				IsForced               bool    `json:"IsForced"`
				Type                   string  `json:"Type"`
				Index                  int     `json:"Index"`
				IsExternal             bool    `json:"IsExternal"`
				IsTextSubtitleStream   bool    `json:"IsTextSubtitleStream"`
				SupportsExternalStream bool    `json:"SupportsExternalStream"`
				Path                   string  `json:"Path,omitempty"`
				Level                  int     `json:"Level"`
				ColorSpace             string  `json:"ColorSpace,omitempty"`
				ColorTransfer          string  `json:"ColorTransfer,omitempty"`
				ColorPrimaries         string  `json:"ColorPrimaries,omitempty"`
				VideoRange             string  `json:"VideoRange,omitempty"`
				VideoRangeType         string  `json:"VideoRangeType,omitempty"`
				BitRate                int     `json:"BitRate,omitempty"`
				BitDepth               int     `json:"BitDepth,omitempty"`
				RefFrames              int     `json:"RefFrames,omitempty"`
				Height                 int     `json:"Height,omitempty"`
				Width                  int     `json:"Width,omitempty"`
				AverageFrameRate       float64 `json:"AverageFrameRate,omitempty"`
				RealFrameRate          float64 `json:"RealFrameRate,omitempty"`
				Profile                string  `json:"Profile,omitempty"`
				AspectRatio            string  `json:"AspectRatio,omitempty"`
				PixelFormat            string  `json:"PixelFormat,omitempty"`
				Title                  string  `json:"Title,omitempty"`
				ChannelLayout          string  `json:"ChannelLayout,omitempty"`
				Channels               int     `json:"Channels,omitempty"`
				SampleRate             int     `json:"SampleRate,omitempty"`
			} `json:"MediaStreams"`
			MediaAttachments    []any `json:"MediaAttachments"`
			Formats             []any `json:"Formats"`
			Bitrate             int   `json:"Bitrate"`
			RequiredHTTPHeaders struct {
			} `json:"RequiredHttpHeaders"`
		} `json:"MediaSources"`
		MediaStreams []struct {
			Codec                  string  `json:"Codec"`
			Language               string  `json:"Language,omitempty"`
			TimeBase               string  `json:"TimeBase"`
			LocalizedUndefined     string  `json:"LocalizedUndefined,omitempty"`
			LocalizedDefault       string  `json:"LocalizedDefault,omitempty"`
			LocalizedForced        string  `json:"LocalizedForced,omitempty"`
			LocalizedExternal      string  `json:"LocalizedExternal,omitempty"`
			DisplayTitle           string  `json:"DisplayTitle"`
			IsInterlaced           bool    `json:"IsInterlaced"`
			IsDefault              bool    `json:"IsDefault"`
			IsForced               bool    `json:"IsForced"`
			Type                   string  `json:"Type"`
			Index                  int     `json:"Index"`
			IsExternal             bool    `json:"IsExternal"`
			IsTextSubtitleStream   bool    `json:"IsTextSubtitleStream"`
			SupportsExternalStream bool    `json:"SupportsExternalStream"`
			Path                   string  `json:"Path,omitempty"`
			Level                  int     `json:"Level"`
			ColorSpace             string  `json:"ColorSpace,omitempty"`
			ColorTransfer          string  `json:"ColorTransfer,omitempty"`
			ColorPrimaries         string  `json:"ColorPrimaries,omitempty"`
			VideoRange             string  `json:"VideoRange,omitempty"`
			VideoRangeType         string  `json:"VideoRangeType,omitempty"`
			BitRate                int     `json:"BitRate,omitempty"`
			BitDepth               int     `json:"BitDepth,omitempty"`
			RefFrames              int     `json:"RefFrames,omitempty"`
			Height                 int     `json:"Height,omitempty"`
			Width                  int     `json:"Width,omitempty"`
			AverageFrameRate       float64 `json:"AverageFrameRate,omitempty"`
			RealFrameRate          float64 `json:"RealFrameRate,omitempty"`
			Profile                string  `json:"Profile,omitempty"`
			AspectRatio            string  `json:"AspectRatio,omitempty"`
			PixelFormat            string  `json:"PixelFormat,omitempty"`
			Title                  string  `json:"Title,omitempty"`
			ChannelLayout          string  `json:"ChannelLayout,omitempty"`
			Channels               int     `json:"Channels,omitempty"`
			SampleRate             int     `json:"SampleRate,omitempty"`
		} `json:"MediaStreams"`
	} `json:"NowPlayingQueueFullItems"`
}
